### ISSUE TITLE
Submissions with older client (1.x) destroys user profile and submission

### ISSUE THREAD

**Issue by NobbZ** [exercism/exercism.io#2742]
In the gitter-support channel there was someone yesterday who was not able to access his profile page anymore, as well as he couldn't see his recent submissions. He used cli version 1.9.

Today another user had the same problem using cli version 1.7

Todays user managed to update cli to a recent version during talk. She resubmitted his exercise and it was available then. Still her profile page is unavailable.

Also she reports to have a weird entry in her dashboard: “Cpp () 0 comments iterations 5” which we understand as exercise cpp of no language, which has 0 comments over 5 iterations.

I've marked the spot in gitter for @kytrinyx by mentioning.

**Comment by masahx** [comment]
Hi, I am second user. 
These "5 iterations" are probably because I sent 5 times my files for "Food Chain" exercise, where problem appeared.
Now I am using new CLI version, but when click on "Exercises" on my account link I got: "Couldn't find that user. ". 
I can't reach page with list of other people's solutions.
My dashboard look like this:

> Cpp () 	0 comments 	iterations 5
> Bob (C++) 	0 comments 	iterations 1
> Word Count (C++) 	0 comments 	iterations 1
> Hamming (C++) 	2 comments 	iterations 2
> Anagram (C++) 	1 comments 	iterations 2 

>You have 6 active problems - _see all

(it didn't list "Food Chain" here. "see all" is link, but when click on it, it gets here
http://exercism.io/masahx with message "Sorry, that's our fault...")

Here is link to my Food Chain submissions http://exercism.io/submissions/0191e067430447c59d03770283919791 - it appeared on Dashboard at "Recently viewed"

**Comment by kytrinyx** [comment]
OK, thanks for reporting this. I'll dig into it today.

**Comment by kytrinyx** [comment]
I've fixed the profile problem, and am deploying it now. Next I'll fix the root cause so that older clients can still submit successfully.

**Comment by kytrinyx** [comment]
Fix isn't quite fixed. Shouldn't have closed it.

**Comment by kytrinyx** [comment]
OK, this time it really is fixed. Deploying.

**Comment by masahx** [comment]
Was it hard? I still have "Cpp () 	0 comments 	iterations 5" on "Dashboard", but now "see all" is better, but first entry there http://exercism.io/masahx is "Cpp". "Exercises" link says "Couldn't find that user. "

**Comment by kytrinyx** [comment]
The dashboard is a different problem--I missed that in the discussion. I've fixed it now.

**Comment by masahx** [comment]
It looks same when I log in, not solved :( (Cpp at Dashboard, no Exercises...)

**Comment by kytrinyx** [comment]
@masahx OK, thanks for letting me know. I'll take another look at this now.

**Comment by kytrinyx** [comment]
OK, I found it. You're going to have to log out and log back in again to clear a cookie, then both of the issues should be fixed. Please let me know if you run into any more problems!

**Comment by masahx** [comment]
My "Exercise" link still doesn't work, and when I deleted some iterations in "Food-chain", iterations which stayed got negative numbers :D. I can't see list with other people's solution, but can see if click on another user
 

    On Saturday, 30 January 2016, 0:57, Katrina Owen <notifications@github.com> wrote:
 

 Closed #2742.—

**Comment by masahx** [comment]
It is OK now, iterations in Food-chain are negative but I don't mind it. "Exercises" link work. Thank you :)

**Comment by kytrinyx** [comment]
whuut. OK, wow, we really screwed up your account! I'll run a script to reset all the iteration counts.

**Comment by masahx** [comment]
Just "Food-chain" has negative iterations :)

**Comment by kytrinyx** [comment]
OK, I think I've got it cleaned up.

**Comment by masahx** [comment]
Food-chain is OK now, I guess that's it

**Comment by kytrinyx** [comment]
Thanks for confirming, and sorry about the mess!

**Comment by masahx** [comment]
It's OK, "exercism" is cool and helpful website!
 

    On Tuesday, 2 February 2016, 23:41, Katrina Owen <notifications@github.com> wrote:
 

 Thanks for confirming, and sorry about the mess!—

**Comment by kytrinyx** [comment]
For anyone else experiencing this issue: I've written a script that can repair accounts that are broken due to this issue. I've run this against production, and it fixed 17 accounts.

**Comment by kytrinyx** [comment]
I have submitted issues using 1.9.0 and 1.7.0 and I've not been able to reproduce the issue. If someone has more information about how to reproduce it, I'd appreciate some help on this.
